import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./_Components/Navbar/Navbar";
import Footer from "./_Components/Footer/Footer";

const pop = Poppins({ subsets: ["latin"] , 
weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] ,
});

export const metadata = {
  title: "Future Tech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={pop.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
